name: Release

on:
  push:
    branches:
      - main
      - '*' 

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - run: npm ci

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
